import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import PageHeader from "../../components/common/PageHeader";
import userService from "../../services/userService";
import { Can } from "../../context/PermissionContext";
export default function UserDetail(){
 const {id}=useParams(); const navigate=useNavigate(); const [user,setUser]=useState(null); const [activity,setActivity]=useState([]); const [meta,setMeta]=useState({page:1,totalPages:1}); const [loading,setLoading]=useState(true);
 const load=()=>Promise.all([userService.getUser(id),userService.getActivity(id,{page:meta.page,limit:20})]).then(([u,a])=>{setUser(u.data.data);setActivity(a.data.data);setMeta(a.data.pagination)}).catch(e=>{toast.error(e.response?.data?.message||"Unable to load user");navigate("/admin/users")}).finally(()=>setLoading(false));
 useEffect(load,[id,meta.page]);
 if(loading&&!user)return <div className="text-center py-5">Loading...</div>;
 return <><PageHeader title={user?.name||"User"} subtitle={user?.email||"User details"}/><div className="row g-4"><div className="col-lg-4"><div className="card shadow-sm"><div className="card-body text-center"><div className="avatar-circle mx-auto mb-3">{user?.name?.slice(0,1)?.toUpperCase()}</div><h3>{user?.name}</h3><div className="text-secondary">{user?.email}</div><div className="mt-3"><span className="badge text-bg-primary me-2">{user?.role}</span><span className={`badge ${user?.status === "active" ? "text-bg-success" : "text-bg-secondary"}`}>{user?.status}</span></div></div><div className="list-group list-group-flush"><Can permission="user-permissions.view"><Link className="list-group-item list-group-item-action" to={`/admin/users/${id}/permissions`}><i className="bi bi-shield-check me-2"/>Manage Permissions</Link></Can><Can permission="users.edit"><Link className="list-group-item list-group-item-action" to={`/admin/users?edit=${id}`}><i className="bi bi-pencil me-2"/>Edit User</Link></Can></div></div></div><div className="col-lg-8"><div className="card shadow-sm"><div className="card-header d-flex justify-content-between"><h3 className="card-title mb-0">Activity</h3><span className="small text-secondary">{meta.total || 0} events</span></div><div className="table-responsive"><table className="table table-hover mb-0"><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Details</th></tr></thead><tbody>{activity.length?activity.map(x=><tr key={x._id}><td className="small">{new Date(x.createdAt).toLocaleString()}</td><td><span className="badge text-bg-light">{x.action}</span></td><td>{x.actorId?.name||"System"}</td><td><code>{JSON.stringify(x.details||{})}</code></td></tr>):<tr><td colSpan="4" className="text-center py-5">No activity found.</td></tr>}</tbody></table></div><div className="card-footer d-flex justify-content-between"><button className="btn btn-sm btn-light" onClick={()=>navigate(-1)}>Back</button><div><button className="btn btn-sm btn-outline-secondary me-2" disabled={meta.page<=1} onClick={()=>setMeta(m=>({...m,page:m.page-1}))}>Previous</button><button className="btn btn-sm btn-outline-secondary" disabled={meta.page>=meta.totalPages} onClick={()=>setMeta(m=>({...m,page:m.page+1}))}>Next</button></div></div></div></div></div></>;
}
