const NOTIFICATION_TYPES = Object.freeze({
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",

  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  ROLE_REMOVED: "ROLE_REMOVED",

  PERMISSION_GRANTED: "PERMISSION_GRANTED",
  PERMISSION_REVOKED: "PERMISSION_REVOKED",

  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",

  ACCOUNT_ACTIVATED: "ACCOUNT_ACTIVATED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",

  SECURITY_ALERT: "SECURITY_ALERT",

  SYSTEM: "SYSTEM",
});

module.exports = {
  NOTIFICATION_TYPES,
};
